### ISSUE TITLE
SNAPSHOT BROKEN?

### ISSUE THREAD

**Issue by fuxiaoalex** [smaldini/grails-events-push#14] opened 2012-08-16 15:16 UTC
Is grails-events-push M2 snapshot broken?

I installed grails-events-push M2 snapshot and events-si M2 snapshot in my app...It works well yesterday afternoon before 2pm EST....

But it  displays the following error right now:

ERROR - core - (resource.ResourceMeta) - Resource not found: /plugins/platform-core-1.0.M3/js/bootstrap.min.js

And event push does't work right now...I have to refresh my page manually  to see the new notification....

Even the Todo Example in Cloudfoundry is broken....If I open two tabs, add one todo in one tab, the other tab will not show the new adding todo automatically...You have to refresh that manually to display the new todo...

Thank you..

**Comment by smaldini** [comment] 2012-08-16 15:25
The cloudfoundry issue is separate, as rabbitmq restarts time by time and I didn't found a way to handle that correctly.

Regarding the bootstrap.min.js, it's a problem inside platform-core and doesn't affect the bus.

Now the problem with your app. Which transport ? Log ?

**Comment by fuxiaoalex** [comment] 2012-08-16 15:30
[11:29:28.053] GET http://localhost:8080/g-eventsbus/eventsbus?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=1.0&X-Atmosphere-Transport=sse&X-Atmosphere-TrackMessageSize=true&X-Cache-Date=0&topics=eventsbus%2CafterInsert%2CafterDelete%2CafterUpdate [HTTP/1.1 200 OK]

sse transport

**Comment by fuxiaoalex** [comment] 2012-08-16 15:31
And the other app using long-polling, met the same problem

**Comment by smaldini** [comment] 2012-08-16 15:33
Is there any js error ?

On Thu, Aug 16, 2012 at 4:31 PM, Alex Fu notifications@github.com wrote:

> And the other app using long-polling, met the same problem
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smaldini/grails-events-push/issues/14#issuecomment-7788950.

## 

## _Stéphane MALDINI_

**Comment by fuxiaoalex** [comment] 2012-08-16 15:38
No , no js error..... The point is that...It works yesterday afternoon....And I don't change anything...It suddenly breaks today...Really weird...

**Comment by smaldini** [comment] 2012-08-16 15:39
I know I need a fixed release.

On Thu, Aug 16, 2012 at 4:38 PM, Alex Fu notifications@github.com wrote:

> No , no js error..... The point is that...It works yesterday
> afternoon....And I don't change anything...It suddenly breaks
> today...Really weird...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/smaldini/grails-events-push/issues/14#issuecomment-7789197.

## 

## _Stéphane MALDINI_

**Comment by smaldini** [comment] 2012-08-16 15:41
btw, I can't reproduce locally. can you share how you connect your listeners, your Events DSL and how you push ?

**Comment by fuxiaoalex** [comment] 2012-08-16 16:01
Just the same as Grails-Todo-Example

in config:
'afterInsert' browser:true, namespace:'gorm',filter:ChatRequest

in frontend js:
window.grailsEvents = new grails.Events('${createLink(uri: '')}', {transport:'sse'});

grailsEvents.on("afterInsert", function(data){
     ...
     ...
     ...
  });

**Comment by fuxiaoalex** [comment] 2012-08-16 16:02
xmlns si: 'http://www.springframework.org/schema/integration'
    xmlns siAmqp: "http://www.springframework.org/schema/integration/amqp"
    xmlns rabbit: "http://www.springframework.org/schema/rabbit"

```
errorsAmqp(com.chat.DumpAmqpErrors)


siAmqp.'publish-subscribe-channel'(id:'gorm://afterInsert','channel-transacted':false,'connection-factory':'rabbitMQConnectionFactory', 'error-handler':"errorsAmqp")
```

In resources.groovy...

**Comment by smaldini** [comment] 2012-08-16 16:15
Mmmh I have redeployed with latest version, looks like working on (http://grailstodos.cloudfoundry.com/todos)

**Comment by fuxiaoalex** [comment] 2012-08-16 16:32
The example still doesn't work for me.....Open two tabs of grail todos.....Add new todo in one of them....The other one will not show the new adding todo automatically....

**Comment by smaldini** [comment] 2012-08-16 16:40
which browser ? mb a js introduced mistake with one browser.

**Comment by fuxiaoalex** [comment] 2012-08-16 16:42
Find the error!

2012-08-16 12:41:03,718 [http-nio-8080-exec-6] WARN  websocket.DefaultWebSocketProcessor  - Failed invoking AtmosphereFramework.doCometSupport()
org.atmosphere.cpr.AtmosphereMappingException: No AtmosphereHandler maps request for /g-eventsbus/eventsbus
    at org.atmosphere.cpr.AsynchronousProcessor.map(AsynchronousProcessor.java:362)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:206)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:120)
    at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:55)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1266)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:210)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:122)
    at org.atmosphere.container.TomcatWebSocketHandler.onOpen(TomcatWebSocketHandler.java:60)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
2012-08-16 12:41:03,720 [http-nio-8080-exec-6] WARN  protocol.SimpleHttpProtocol  - org.atmosphere.cpr.AtmosphereMappingException: No AtmosphereHandler maps request for /g-eventsbus/eventsbus Status 500 Message Server Error

Do you know how to solve that?

**Comment by smaldini** [comment] 2012-08-16 16:56
Maxi weird. Is there another atmosphere plugin ? Do you have grails.tomcat.nio = true in BuildConfig ? can you produce a war and give me the web.xml ?

**Comment by fuxiaoalex** [comment] 2012-08-16 17:07
No...Only events push and events-si....I put the war in our shared dropbox folder.....The folder is named "event-push-test", the war file name is "grailsTodos-0.1.war". Plz check it. Thanks.

**Comment by smaldini** [comment] 2012-08-16 17:55
Mmmh you have atmosphere.xml and your web.xml has:

``` xml
    <servlet>
        <description>AtmosphereServlet</description>
        <servlet-name>AtmosphereServlet</servlet-name>
        <servlet-class>org.atmosphere.cpr.AtmosphereServlet</servlet-class>
        <load-on-startup>0</load-on-startup>
    </servlet>
```

plus a strange double 

``` xml
         <init-param>
            <param-name>org.atmosphere.useWebSocket</param-name>
            <param-value/>
        </init-param>
```

(Do you have any related config key in your Config ??)

**Comment by fuxiaoalex** [comment] 2012-08-16 18:03
What do you mean by plus a strange double

```
     <init-param>
        <param-name>org.atmosphere.useWebSocket</param-name>
        <param-value/>
    </init-param>
```

I didn't see that......

**Comment by fuxiaoalex** [comment] 2012-08-16 18:08
I didn't set that parameter...I think the default value is true.....

**Comment by smaldini** [comment] 2012-08-16 18:10
This doesn't mind, I have this problem as well and it works anyway (its fixed in a future snapshot).
The real problem is the AtmosphereServlet in your web.xml I think. Why is there an AtmosphereServlet ? and Why is there a META-INF/atmosphere.xml ? I guess this causes a race condition between two atmosphere factories

**Comment by fuxiaoalex** [comment] 2012-08-16 18:14
Because I have another chat controller which is using atmosphere handler, you can see that handler in src/groovy....And this application is running perfectly for almost 3 weeks...And only met this problem since yesterday night..

**Comment by smaldini** [comment] 2012-08-16 18:28
Can't start your app since it requires credentials for rabbitmq. But I'm still not sure about what is causing issue so far in your app, the only big change is the size tracking (webconsole could help to debug that) and the disconnect/reconnect for new topics. These both changes work in the standard sample but I didn't test with a combined use with Atmosphere.

**Comment by fuxiaoalex** [comment] 2012-08-16 18:33
you can change that in config to username="guest" password="guest"

And another thing is that my chat websocket connection is now reconnecting every minute, and the default setting is actually 5 minutes.

2012-08-16 14:30:14,711 [http-nio-8080-exec-5] DEBUG http11.Http11NioProcessor  - Error parsing HTTP request header
java.io.EOFException: Unexpected EOF read on the socket
    at org.apache.coyote.http11.InternalNioInputBuffer.readSocket(InternalNioInputBuffer.java:460)
    at org.apache.coyote.http11.InternalNioInputBuffer.parseRequestLine(InternalNioInputBuffer.java:245)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:926)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1620)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)

**Comment by smaldini** [comment] 2012-08-16 18:55
You gave me a war file, a precompiled version, how can I change the config :) ?

About the websocket, I've seen that, I need to investigate this issue.

**Comment by fuxiaoalex** [comment] 2012-08-16 19:19
Sorry about that, Stephane...I've send an email to your VMware mailbox. Plz check it.

**Comment by fuxiaoalex** [comment] 2012-08-16 23:41
In grails-events-push / src / java / org / grails / plugin / platform / events / push / GrailsMeteorServlet.java 

I don't know why you write if (servletClass == null) { }?

If you don't have this, isn't it possible to add multiple handlers?

Thanks.

**Closed as completed** 2013-01-15 21:41 UTC
